In [1]:
# import packages
import pandas as pd
import numpy as np

In [2]:
# if, elif, else statement goes through construct only once!
# While loop = repeated if statement
# The code is executed over and over again, as long as the condition is True
# while condition:
#     expression

In [3]:
# example_1
error = 50
while error > 1:
    error = error/4
    print(error)
    # when error = 0.78125, the loop will be terminated

12.5
3.125
0.78125


In [4]:
# example_2
x = 1
while x < 4 :
    print(x)
    x = x + 1
    # when x = 4, the loop will be terminated

1
2
3


In [5]:
# # example_3
# inverted pendulum
# if there's an offset from standing perfectly straight, the while loop will incrementally fix this offset.

# Initialize offset
offset =8

# Code the while loop
while offset != 0:
    print('correcting...')
    offset =offset - 1
    print(offset)

correcting...
7
correcting...
6
correcting...
5
correcting...
4
correcting...
3
correcting...
2
correcting...
1
correcting...
0


In [6]:
# Initialize offset
offset = -6

# Code the while loop
while offset != 0 :
    print("correcting...")
    if offset > 0 :
      offset = offset -1
    else :
      offset = offset +1    
    print(offset)

correcting...
-5
correcting...
-4
correcting...
-3
correcting...
-2
correcting...
-1
correcting...
0


In [7]:
# for loop
# for var in seq:
#     expression
# for each var (variable) in seq (sequence), execute expression 

In [8]:
# loop over a list
# example_1
# fam_heights list
fam_heights = [1.73, 1.68, 1.71, 1.89]

# Code the for loop
for height in fam_heights:
    print(height)

1.73
1.68
1.71
1.89


In [9]:
# Python List Index()
# https://www.datacamp.com/community/tutorials/python-list-index

In [10]:
# loop over a list
# example_2
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for room in areas:
    print(room)

11.25
18.0
20.0
10.75
9.5


In [11]:
# loop over a list using enumerate()

# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for index, room in enumerate(areas) :
    print("room " + str(index)+": " + str(room))

room 0: 11.25
room 1: 18.0
room 2: 20.0
room 3: 10.75
room 4: 9.5


In [12]:
# loop over a list using enumerate() starting with index = 1
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for index, area in enumerate(areas) :
    print("room " + str(index+1) + ": " + str(area))

room 1: 11.25
room 2: 18.0
room 3: 20.0
room 4: 10.75
room 5: 9.5


In [13]:
# Loop over list of lists
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
# Code the for loop
# You can use x[0] to access the name of the room and x[1] to access the corresponding area.
for x in house :
    print("the " + x[0] + " is " + str(x[1]) + " sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


In [14]:
# loop over a string
for c in "family":
    print(c.capitalize())

F
A
M
I
L
Y


In [15]:
# loop over a dictionary
# we use .items() method to iterate over a dictionary
# Definition of dictionary
europe = {'spain':'madrid',
          'france':'paris', 
          'germany':'berlin',
          'norway':'oslo', 
          'italy':'rome', 
          'poland':'warsaw', 
          'austria':'vienna' }
          
# Iterate over europe
for key, value in europe.items():
    print("the capital of " + key + " is " + value)

the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna


In [16]:
# loop over numpy array
# Create 1-D np_array for height & weight
np_height = np.array([74, 74, 72, 75, 75, 73])
np_weight = np.array([180, 215, 210, 205, 190, 195])

In [17]:
np_height

array([74, 74, 72, 75, 75, 73])

In [18]:
np_weight

array([180, 215, 210, 205, 190, 195])

In [19]:
# loop over 1-D numpy array
# For loop over np_height
for x in np_height:
    print(str(x)+" inches")

74 inches
74 inches
72 inches
75 inches
75 inches
73 inches


In [20]:
# Create 2-D np_array for baseball
np_baseball = np.array([np_height, np_weight])
np_baseball

array([[ 74,  74,  72,  75,  75,  73],
       [180, 215, 210, 205, 190, 195]])

In [21]:
# We use np.nditer(2-D np_array) function to iterate over a 2-D numpy array
# For loop over np_baseball
for x in np.nditer(np_baseball):
    print(x)

74
74
72
75
75
73
180
215
210
205
190
195


In [22]:
# in case we do not use np.nditer(2-D np_array) function
for x in np_baseball:
    print(x)

[74 74 72 75 75 73]
[180 215 210 205 190 195]


In [23]:
# loop over a Pandas DataFrame
# Iterating over a Pandas DataFrame is typically done with the iterrows() method
# Import cars data
cars_df = pd.read_csv('cars.csv', index_col = 0)
cars_df

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [24]:
# Iterate over rows of cars DataFrame
# Note that the output row data that's generated by iterrows() on every run is a Pandas Series
for lab, row in cars_df.iterrows():
    print(lab)
    print(row)

US
cars_per_cap              809
country         United States
drives_right             True
Name: US, dtype: object
AUS
cars_per_cap          731
country         Australia
drives_right        False
Name: AUS, dtype: object
JAP
cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
IN
cars_per_cap       18
country         India
drives_right    False
Name: IN, dtype: object
RU
cars_per_cap       200
country         Russia
drives_right      True
Name: RU, dtype: object
MOR
cars_per_cap         70
country         Morocco
drives_right       True
Name: MOR, dtype: object
EG
cars_per_cap       45
country         Egypt
drives_right     True
Name: EG, dtype: object


In [25]:
# Adapt for loop
for lab, row in cars_df.iterrows() :
    print(lab + ": " + str(row['country']) + ": " + str(row['cars_per_cap']))

US: United States: 809
AUS: Australia: 731
JAP: Japan: 588
IN: India: 18
RU: Russia: 200
MOR: Morocco: 70
EG: Egypt: 45


In [26]:
cars_df

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [27]:
# Code for loop that adds COUNTRY column to cars DataFrame
for lab, row in cars_df.iterrows() :
    cars_df.loc[lab, "COUNTRY"] = row["country"].upper()

In [28]:
cars_df

cars_per_cap        country  drives_right        COUNTRY
US            809  United States          True  UNITED STATES
AUS           731      Australia         False      AUSTRALIA
JAP           588          Japan         False          JAPAN
IN             18          India         False          INDIA
RU            200         Russia          True         RUSSIA
MOR            70        Morocco          True        MOROCCO
EG             45          Egypt          True          EGYPT

In [29]:
# Using iterrows() to iterate over every observation of a Pandas DataFrame is easy to understand, but not very efficient. 
# On every iteration, you're creating a new Pandas Series.
# If you want to add a column to a DataFrame by calling a function on another column,
# the iterrows() method in combination with a for loop is not the preferred way to go.
# Instead, you'll want to use apply().
# Use .apply(str.upper)
cars_df["COUNTRY"] = cars_df["country"].apply(str.upper)
cars_df

cars_per_cap        country  drives_right        COUNTRY
US            809  United States          True  UNITED STATES
AUS           731      Australia         False      AUSTRALIA
JAP           588          Japan         False          JAPAN
IN             18          India         False          INDIA
RU            200         Russia          True         RUSSIA
MOR            70        Morocco          True        MOROCCO
EG             45          Egypt          True          EGYPT

In [30]:
# Add country_length column to cars DataFrame
# Use .apply(str.upper)
cars_df["country_length"] = cars_df["country"].apply(len)
cars_df

cars_per_cap        country  drives_right        COUNTRY  country_length
US            809  United States          True  UNITED STATES              13
AUS           731      Australia         False      AUSTRALIA               9
JAP           588          Japan         False          JAPAN               5
IN             18          India         False          INDIA               5
RU            200         Russia          True         RUSSIA               6
MOR            70        Morocco          True        MOROCCO               7
EG             45          Egypt          True          EGYPT               5