In [1]:
# As long as the types of the two objects are the same, these two objects can be compared.
# Typically Python can not tell how two objects with different types relate
# different numeric types such as floats and integers are exceptions
# Comparison operators
# {<, >, >=, <=, ==, !=}

In [2]:
# Comparison of integers
2 < 3

True

In [3]:
2 == 3

False

In [4]:
-5*15 != 75

True

In [5]:
3 <= 3

True

In [6]:
2 == (1 + 1)

True

In [7]:
x = 2
y = 3
x < y

True

In [8]:
# Comparison of two numbers (objects) with two different types
2.5 <= 3

True

In [9]:
# Comparison of stringsn
"intermediate" != "python"

True

In [10]:
"Python" == "python"

False

In [11]:
# alpha comes alphabetically before beta
"alpha" <= "beta"

True

In [12]:
# Comparison of booleans
True != False

True

In [13]:
# Note: a boolean is a special kind of integer: 
# True corresponds to 1
# False corresponds to 0
True == 1

True

In [14]:
False == 0

True

In [15]:
True > False

True

In [16]:
# import NumPy package
import numpy as np

In [17]:
# Compare arrays (NumPy Arrays)
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [18]:
my_house >= 18

array([ True,  True, False, False])

In [19]:
# compare two NumPy arrays element-wise
my_house <= your_house

array([False,  True,  True, False])

In [20]:
# Boolean operators such as {and, or and not}
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0

In [21]:
my_kitchen > 10 and my_kitchen < 18

False

In [22]:
my_kitchen < 14 or my_kitchen > 17

True

In [23]:
2 * my_kitchen < 3 * your_kitchen

True

In [24]:
not True

False

In [25]:
not False

True

In [26]:
# Define variables
x = 8
y = 9
not(not(x < 3) and not(y > 14 or y > 10))

False

In [27]:
# Boolean operators with NumPy
# np.logical_and()
# np.logical_or()
# np.logical_not()
# Create arrays
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [28]:
my_house

array([18.  , 20.  , 10.75,  9.5 ])

In [29]:
your_house

array([14.  , 24.  , 14.25,  9.  ])

In [30]:
np.logical_or(my_house > 18.5, my_house <10)

array([False,  True, False,  True])

In [31]:
my_house[np.logical_or(my_house > 18.5, my_house <10)]

array([20. ,  9.5])

In [32]:
np.logical_and(my_house < 11,  your_house <11)

array([False, False, False,  True])

In [33]:
# Conditional statements
# if, else, elif

In [34]:
# if statement

# if condition:
#         expression

In [35]:
z = 4

if z % 2 ==0:   # True
    print("checking " + str(z))
    print("z is even")

checking 4
z is even


In [36]:
# if .. else statement

# if condition:
#         expression
# else:
#         expression

In [37]:
z = 5

if z % 2 ==0:   # False
    print("z is even")
else:           # True
    print("z is odd")

z is odd


In [38]:
# elif statement

# if condition:
#         expression
# elif condition:
#         expression
# else:
#         expression

In [39]:
# Define variable
z = 3

if z % 2 ==0:   
    print("z is divisible by 2")  # False
elif z % 3 ==0: 
    print("z is divisible by 3")  # True
else:
    print("z is neither divisible by 2 nor by 3")

z is divisible by 3


In [40]:
# Define variable
z = 6

if z % 2 ==0:   
    print("z is divisible by 2")  # True
elif z % 3 ==0: 
    print("z is divisible by 3")  # Never reached
else:
    print("z is neither divisible by 2 nor by 3")

z is divisible by 2


In [41]:
# Define variable
area = 10.0

if(area < 9) :
    print("small")  # False
elif(area < 12) :
    print("medium") # True
else :
    print("large")  # Never reached

medium


In [42]:
# Define variables
room = "bed"
area = 14.0

# if-elif-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")  # False
elif room == "bed":
    print("looking around in the bedroom.")  # True
else :
    print("looking around elsewhere.")       # Never reached

# if-elif-else construct for area
if area > 15 :
    print("big place!")  # False
elif area >10:
    print('medium size, nice!')  # True  
else :
    print("pretty small.")  # Never reached

looking around in the bedroom.
medium size, nice!
